version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11 #3.8
    commands:
      - echo "Installing dependencies..."
      - echo "none tbh"
  build:
    commands:
      - echo "Zipping deployment packages for lambdas..."\
      #- cd lambdas/index-photos
      - cd lambdas/index-photos
      - zip -r9 deployment_index.zip * #lambdas/index-photos/*
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://deployment_index.zip
      - echo "update index-photos"
      - cd 
      - ls
      - cd lambdas/search-photos
      - zip -r9 deployment_search.zip * #lambdas/search-photos/*
      - echo "update index-photos"
  #post_build:
  #  commands:
      #- echo "Updating Lambda Functions..."
      #- aws lambda update-function-code --function-name index-photos --zip-file fileb://deployment_index.zip
      #- aws lambda update-function-code --function-name search-photos --zip-file fileb://deployment_search.zip
